// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teaserByteUtils.proto

package com.bizosys.hsearch.teaser.filter;

public final class TeaserByteUtils {
  private TeaserByteUtils() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TeaserVO extends
      com.google.protobuf.GeneratedMessage {
    // Use TeaserVO.newBuilder() to construct.
    private TeaserVO() {
      initFields();
    }
    private TeaserVO(boolean noInit) {}
    
    private static final TeaserVO defaultInstance;
    public static TeaserVO getDefaultInstance() {
      return defaultInstance;
    }
    
    public TeaserVO getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_fieldAccessorTable;
    }
    
    // required string sid = 1;
    public static final int SID_FIELD_NUMBER = 1;
    private boolean hasSid;
    private java.lang.String sid_ = "";
    public boolean hasSid() { return hasSid; }
    public java.lang.String getSid() { return sid_; }
    
    // optional string url = 2;
    public static final int URL_FIELD_NUMBER = 2;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // optional bytes title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private boolean hasTitle;
    private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasTitle() { return hasTitle; }
    public com.google.protobuf.ByteString getTitle() { return title_; }
    
    // optional bytes teaser = 4;
    public static final int TEASER_FIELD_NUMBER = 4;
    private boolean hasTeaser;
    private com.google.protobuf.ByteString teaser_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasTeaser() { return hasTeaser; }
    public com.google.protobuf.ByteString getTeaser() { return teaser_; }
    
    // optional bytes preview = 5;
    public static final int PREVIEW_FIELD_NUMBER = 5;
    private boolean hasPreview;
    private com.google.protobuf.ByteString preview_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPreview() { return hasPreview; }
    public com.google.protobuf.ByteString getPreview() { return preview_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasSid) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSid()) {
        output.writeString(1, getSid());
      }
      if (hasUrl()) {
        output.writeString(2, getUrl());
      }
      if (hasTitle()) {
        output.writeBytes(3, getTitle());
      }
      if (hasTeaser()) {
        output.writeBytes(4, getTeaser());
      }
      if (hasPreview()) {
        output.writeBytes(5, getPreview());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSid());
      }
      if (hasUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUrl());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitle());
      }
      if (hasTeaser()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTeaser());
      }
      if (hasPreview()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPreview());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO result;
      
      // Construct using com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO();
        return builder;
      }
      
      protected com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO.getDescriptor();
      }
      
      public com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO getDefaultInstanceForType() {
        return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO) {
          return mergeFrom((com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO other) {
        if (other == com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO.getDefaultInstance()) return this;
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasTeaser()) {
          setTeaser(other.getTeaser());
        }
        if (other.hasPreview()) {
          setPreview(other.getPreview());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSid(input.readString());
              break;
            }
            case 18: {
              setUrl(input.readString());
              break;
            }
            case 26: {
              setTitle(input.readBytes());
              break;
            }
            case 34: {
              setTeaser(input.readBytes());
              break;
            }
            case 42: {
              setPreview(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required string sid = 1;
      public boolean hasSid() {
        return result.hasSid();
      }
      public java.lang.String getSid() {
        return result.getSid();
      }
      public Builder setSid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSid = true;
        result.sid_ = value;
        return this;
      }
      public Builder clearSid() {
        result.hasSid = false;
        result.sid_ = getDefaultInstance().getSid();
        return this;
      }
      
      // optional string url = 2;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = getDefaultInstance().getUrl();
        return this;
      }
      
      // optional bytes title = 3;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public com.google.protobuf.ByteString getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // optional bytes teaser = 4;
      public boolean hasTeaser() {
        return result.hasTeaser();
      }
      public com.google.protobuf.ByteString getTeaser() {
        return result.getTeaser();
      }
      public Builder setTeaser(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTeaser = true;
        result.teaser_ = value;
        return this;
      }
      public Builder clearTeaser() {
        result.hasTeaser = false;
        result.teaser_ = getDefaultInstance().getTeaser();
        return this;
      }
      
      // optional bytes preview = 5;
      public boolean hasPreview() {
        return result.hasPreview();
      }
      public com.google.protobuf.ByteString getPreview() {
        return result.getPreview();
      }
      public Builder setPreview(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPreview = true;
        result.preview_ = value;
        return this;
      }
      public Builder clearPreview() {
        result.hasPreview = false;
        result.preview_ = getDefaultInstance().getPreview();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.teaser.filter.TeaserVO)
    }
    
    static {
      defaultInstance = new TeaserVO(true);
      com.bizosys.hsearch.teaser.filter.TeaserByteUtils.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.teaser.filter.TeaserVO)
  }
  
  public static final class FindTeaser extends
      com.google.protobuf.GeneratedMessage {
    // Use FindTeaser.newBuilder() to construct.
    private FindTeaser() {
      initFields();
    }
    private FindTeaser(boolean noInit) {}
    
    private static final FindTeaser defaultInstance;
    public static FindTeaser getDefaultInstance() {
      return defaultInstance;
    }
    
    public FindTeaser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_fieldAccessorTable;
    }
    
    // required int32 teaserLength = 1;
    public static final int TEASERLENGTH_FIELD_NUMBER = 1;
    private boolean hasTeaserLength;
    private int teaserLength_ = 0;
    public boolean hasTeaserLength() { return hasTeaserLength; }
    public int getTeaserLength() { return teaserLength_; }
    
    // repeated bytes matchWords = 2;
    public static final int MATCHWORDS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> matchWords_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getMatchWordsList() {
      return matchWords_;
    }
    public int getMatchWordsCount() { return matchWords_.size(); }
    public com.google.protobuf.ByteString getMatchWords(int index) {
      return matchWords_.get(index);
    }
    
    // repeated int32 hids = 3;
    public static final int HIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> hids_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getHidsList() {
      return hids_;
    }
    public int getHidsCount() { return hids_.size(); }
    public int getHids(int index) {
      return hids_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTeaserLength) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTeaserLength()) {
        output.writeInt32(1, getTeaserLength());
      }
      for (com.google.protobuf.ByteString element : getMatchWordsList()) {
        output.writeBytes(2, element);
      }
      for (int element : getHidsList()) {
        output.writeInt32(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTeaserLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTeaserLength());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getMatchWordsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getMatchWordsList().size();
      }
      {
        int dataSize = 0;
        for (int element : getHidsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getHidsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser result;
      
      // Construct using com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser();
        return builder;
      }
      
      protected com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser.getDescriptor();
      }
      
      public com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser getDefaultInstanceForType() {
        return com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.matchWords_ != java.util.Collections.EMPTY_LIST) {
          result.matchWords_ =
            java.util.Collections.unmodifiableList(result.matchWords_);
        }
        if (result.hids_ != java.util.Collections.EMPTY_LIST) {
          result.hids_ =
            java.util.Collections.unmodifiableList(result.hids_);
        }
        com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser) {
          return mergeFrom((com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser other) {
        if (other == com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser.getDefaultInstance()) return this;
        if (other.hasTeaserLength()) {
          setTeaserLength(other.getTeaserLength());
        }
        if (!other.matchWords_.isEmpty()) {
          if (result.matchWords_.isEmpty()) {
            result.matchWords_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.matchWords_.addAll(other.matchWords_);
        }
        if (!other.hids_.isEmpty()) {
          if (result.hids_.isEmpty()) {
            result.hids_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.hids_.addAll(other.hids_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTeaserLength(input.readInt32());
              break;
            }
            case 18: {
              addMatchWords(input.readBytes());
              break;
            }
            case 24: {
              addHids(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addHids(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required int32 teaserLength = 1;
      public boolean hasTeaserLength() {
        return result.hasTeaserLength();
      }
      public int getTeaserLength() {
        return result.getTeaserLength();
      }
      public Builder setTeaserLength(int value) {
        result.hasTeaserLength = true;
        result.teaserLength_ = value;
        return this;
      }
      public Builder clearTeaserLength() {
        result.hasTeaserLength = false;
        result.teaserLength_ = 0;
        return this;
      }
      
      // repeated bytes matchWords = 2;
      public java.util.List<com.google.protobuf.ByteString> getMatchWordsList() {
        return java.util.Collections.unmodifiableList(result.matchWords_);
      }
      public int getMatchWordsCount() {
        return result.getMatchWordsCount();
      }
      public com.google.protobuf.ByteString getMatchWords(int index) {
        return result.getMatchWords(index);
      }
      public Builder setMatchWords(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.matchWords_.set(index, value);
        return this;
      }
      public Builder addMatchWords(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.matchWords_.isEmpty()) {
          result.matchWords_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.matchWords_.add(value);
        return this;
      }
      public Builder addAllMatchWords(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.matchWords_.isEmpty()) {
          result.matchWords_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.matchWords_);
        return this;
      }
      public Builder clearMatchWords() {
        result.matchWords_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated int32 hids = 3;
      public java.util.List<java.lang.Integer> getHidsList() {
        return java.util.Collections.unmodifiableList(result.hids_);
      }
      public int getHidsCount() {
        return result.getHidsCount();
      }
      public int getHids(int index) {
        return result.getHids(index);
      }
      public Builder setHids(int index, int value) {
        result.hids_.set(index, value);
        return this;
      }
      public Builder addHids(int value) {
        if (result.hids_.isEmpty()) {
          result.hids_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.hids_.add(value);
        return this;
      }
      public Builder addAllHids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.hids_.isEmpty()) {
          result.hids_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.hids_);
        return this;
      }
      public Builder clearHids() {
        result.hids_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bizosys.hsearch.teaser.filter.FindTeaser)
    }
    
    static {
      defaultInstance = new FindTeaser(true);
      com.bizosys.hsearch.teaser.filter.TeaserByteUtils.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bizosys.hsearch.teaser.filter.FindTeaser)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025teaserByteUtils.proto\022!com.bizosys.hse" +
      "arch.teaser.filter\"T\n\010TeaserVO\022\013\n\003sid\030\001 " +
      "\002(\t\022\013\n\003url\030\002 \001(\t\022\r\n\005title\030\003 \001(\014\022\016\n\006tease" +
      "r\030\004 \001(\014\022\017\n\007preview\030\005 \001(\014\"D\n\nFindTeaser\022\024" +
      "\n\014teaserLength\030\001 \002(\005\022\022\n\nmatchWords\030\002 \003(\014" +
      "\022\014\n\004hids\030\003 \003(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_teaser_filter_TeaserVO_descriptor,
              new java.lang.String[] { "Sid", "Url", "Title", "Teaser", "Preview", },
              com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO.class,
              com.bizosys.hsearch.teaser.filter.TeaserByteUtils.TeaserVO.Builder.class);
          internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bizosys_hsearch_teaser_filter_FindTeaser_descriptor,
              new java.lang.String[] { "TeaserLength", "MatchWords", "Hids", },
              com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser.class,
              com.bizosys.hsearch.teaser.filter.TeaserByteUtils.FindTeaser.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
